package com.luna.bpm.conf.entity;

// Generated by Hibernate Tools
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.luna.common.entity.BaseEntity;

/**
 * BpmConfNode .
 * 
 * @author Lingo
 */
@Entity
@Table(name = "BPM_CONF_NODE")
public class BpmConfNode extends BaseEntity<Long> {
    private static final long serialVersionUID = 0L;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "CONF_BASE_ID")
    private BpmConfBase bpmConfBase;

    @Column(name = "CODE", length = 200)
    private String code;

    @Column(name = "NAME", length = 200)
    private String name;

    @Column(name = "TYPE", length = 200)
    private String type;

    @Column(name = "CONF_USER")
    private Integer confUser;

    @Column(name = "CONF_LISTENER")
    private Integer confListener;

    @Column(name = "CONF_RULE")
    private Integer confRule;

    @Column(name = "CONF_FORM")
    private Integer confForm;

    @Column(name = "CONF_OPERATION")
    private Integer confOperation;

    @Column(name = "CONF_NOTICE")
    private Integer confNotice;

    @Column(name = "PRIORITY")
    private Integer priority;

    /** . */
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "bpmConfNode")
    private Set<BpmConfListener> bpmConfListeners = new HashSet<BpmConfListener>(
            0);

    /** . */
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "bpmConfNode")
    private Set<BpmConfNotice> bpmConfNotices = new HashSet<BpmConfNotice>(0);

    /** . */
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "bpmConfNode")
    private Set<BpmConfUser> bpmConfUsers = new HashSet<BpmConfUser>(0);

    /** . */
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "bpmConfNode")
    private Set<BpmConfCountersign> bpmConfCountersigns = new HashSet<BpmConfCountersign>(
            0);

    /** . */
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "bpmConfNode")
    private Set<BpmConfForm> bpmConfForms = new HashSet<BpmConfForm>(0);

    /** . */
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "bpmConfNode")
    private Set<BpmConfRule> bpmConfRules = new HashSet<BpmConfRule>(0);

    /** . */
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "bpmConfNode")
    private Set<BpmConfOperation> bpmConfOperations = new HashSet<BpmConfOperation>(
            0);

    public BpmConfNode() {
    }

    public BpmConfNode(BpmConfBase bpmConfBase, String code, String name,
            String type, Integer confUser, Integer confListener,
            Integer confRule, Integer confForm, Integer confOperation,
            Integer confNotice, Integer priority,
            Set<BpmConfListener> bpmConfListeners,
            Set<BpmConfNotice> bpmConfNotices, Set<BpmConfUser> bpmConfUsers,
            Set<BpmConfCountersign> bpmConfCountersigns,
            Set<BpmConfForm> bpmConfForms, Set<BpmConfRule> bpmConfRules,
            Set<BpmConfOperation> bpmConfOperations) {
        this.bpmConfBase = bpmConfBase;
        this.code = code;
        this.name = name;
        this.type = type;
        this.confUser = confUser;
        this.confListener = confListener;
        this.confRule = confRule;
        this.confForm = confForm;
        this.confOperation = confOperation;
        this.confNotice = confNotice;
        this.priority = priority;
        this.bpmConfListeners = bpmConfListeners;
        this.bpmConfNotices = bpmConfNotices;
        this.bpmConfUsers = bpmConfUsers;
        this.bpmConfCountersigns = bpmConfCountersigns;
        this.bpmConfForms = bpmConfForms;
        this.bpmConfRules = bpmConfRules;
        this.bpmConfOperations = bpmConfOperations;
    }

    /** @return null. */
    public BpmConfBase getBpmConfBase() {
        return this.bpmConfBase;
    }

    /**
     * @param bpmConfBase
     *            null.
     */
    public void setBpmConfBase(BpmConfBase bpmConfBase) {
        this.bpmConfBase = bpmConfBase;
    }

    /** @return null. */
    public String getCode() {
        return this.code;
    }

    /**
     * @param code
     *            null.
     */
    public void setCode(String code) {
        this.code = code;
    }

    /** @return null. */
    public String getName() {
        return this.name;
    }

    /**
     * @param name
     *            null.
     */
    public void setName(String name) {
        this.name = name;
    }

    /** @return null. */
    public String getType() {
        return this.type;
    }

    /**
     * @param type
     *            null.
     */
    public void setType(String type) {
        this.type = type;
    }

    /** @return null. */
    public Integer getConfUser() {
        return this.confUser;
    }

    /**
     * @param confUser
     *            null.
     */
    public void setConfUser(Integer confUser) {
        this.confUser = confUser;
    }

    /** @return null. */
    public Integer getConfListener() {
        return this.confListener;
    }

    /**
     * @param confListener
     *            null.
     */
    public void setConfListener(Integer confListener) {
        this.confListener = confListener;
    }

    /** @return null. */
    public Integer getConfRule() {
        return this.confRule;
    }

    /**
     * @param confRule
     *            null.
     */
    public void setConfRule(Integer confRule) {
        this.confRule = confRule;
    }

    /** @return null. */
    public Integer getConfForm() {
        return this.confForm;
    }

    /**
     * @param confForm
     *            null.
     */
    public void setConfForm(Integer confForm) {
        this.confForm = confForm;
    }

    /** @return null. */
    public Integer getConfOperation() {
        return this.confOperation;
    }

    /**
     * @param confOperation
     *            null.
     */
    public void setConfOperation(Integer confOperation) {
        this.confOperation = confOperation;
    }

    /** @return null. */
    public Integer getConfNotice() {
        return this.confNotice;
    }

    /**
     * @param confNotice
     *            null.
     */
    public void setConfNotice(Integer confNotice) {
        this.confNotice = confNotice;
    }

    /** @return null. */
    public Integer getPriority() {
        return this.priority;
    }

    /**
     * @param priority
     *            null.
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /** @return . */
    public Set<BpmConfListener> getBpmConfListeners() {
        return this.bpmConfListeners;
    }

    /**
     * @param bpmConfListeners
     *            .
     */
    public void setBpmConfListeners(Set<BpmConfListener> bpmConfListeners) {
        this.bpmConfListeners = bpmConfListeners;
    }

    /** @return . */
    public Set<BpmConfNotice> getBpmConfNotices() {
        return this.bpmConfNotices;
    }

    /**
     * @param bpmConfNotices
     *            .
     */
    public void setBpmConfNotices(Set<BpmConfNotice> bpmConfNotices) {
        this.bpmConfNotices = bpmConfNotices;
    }

    /** @return . */
    public Set<BpmConfUser> getBpmConfUsers() {
        return this.bpmConfUsers;
    }

    /**
     * @param bpmConfUsers
     *            .
     */
    public void setBpmConfUsers(Set<BpmConfUser> bpmConfUsers) {
        this.bpmConfUsers = bpmConfUsers;
    }

    /** @return . */
    public Set<BpmConfCountersign> getBpmConfCountersigns() {
        return this.bpmConfCountersigns;
    }

    /**
     * @param bpmConfCountersigns
     *            .
     */
    public void setBpmConfCountersigns(
            Set<BpmConfCountersign> bpmConfCountersigns) {
        this.bpmConfCountersigns = bpmConfCountersigns;
    }

    /** @return . */
    public Set<BpmConfForm> getBpmConfForms() {
        return this.bpmConfForms;
    }

    /**
     * @param bpmConfForms
     *            .
     */
    public void setBpmConfForms(Set<BpmConfForm> bpmConfForms) {
        this.bpmConfForms = bpmConfForms;
    }

    /** @return . */
    public Set<BpmConfRule> getBpmConfRules() {
        return this.bpmConfRules;
    }

    /**
     * @param bpmConfRules
     *            .
     */
    public void setBpmConfRules(Set<BpmConfRule> bpmConfRules) {
        this.bpmConfRules = bpmConfRules;
    }

    /** @return . */
    public Set<BpmConfOperation> getBpmConfOperations() {
        return this.bpmConfOperations;
    }

    /**
     * @param bpmConfOperations
     *            .
     */
    public void setBpmConfOperations(Set<BpmConfOperation> bpmConfOperations) {
        this.bpmConfOperations = bpmConfOperations;
    }
}
