package com.luna.bpm.conf.entity;

// Generated by Hibernate Tools
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.luna.bpm.process.entity.BpmProcess;
import com.luna.common.entity.BaseEntity;

/**
 * BpmConfBase .
 * 
 * @author Lingo
 */
@Entity
@Table(name = "BPM_CONF_BASE")
public class BpmConfBase extends BaseEntity<Long> {
    private static final long serialVersionUID = 0L;

    @Column(name = "PROCESS_DEFINITION_ID", length = 200)
    private String processDefinitionId;

    @Column(name = "PROCESS_DEFINITION_NAME", length = 200)
    private String processDefinitionName;

    @Column(name = "PROCESS_DEFINITION_KEY", length = 200)
    private String processDefinitionKey;

    @Column(name = "PROCESS_DEFINITION_VERSION")
    private Integer processDefinitionVersion;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "bpmConfBase")
    private Set<BpmConfNode> bpmConfNodes = new HashSet<BpmConfNode>(0);

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "bpmConfBase")
    private Set<BpmProcess> bpmProcesses = new HashSet<BpmProcess>(0);

    public BpmConfBase() {
    }

    public BpmConfBase(String processDefinitionId, String processDefinitionName, String processDefinitionKey,
            Integer processDefinitionVersion, Set<BpmConfNode> bpmConfNodes,
            Set<BpmProcess> bpmProcesses) {
        this.processDefinitionId = processDefinitionId;
        this.processDefinitionKey = processDefinitionKey;
        this.processDefinitionName = processDefinitionName;
        this.processDefinitionVersion = processDefinitionVersion;
        this.bpmConfNodes = bpmConfNodes;
        this.bpmProcesses = bpmProcesses;
    }

    public String getProcessDefinitionName() {
		return processDefinitionName;
	}

	public void setProcessDefinitionName(String processDefinitionName) {
		this.processDefinitionName = processDefinitionName;
	}

	/** @return null. */
    public String getProcessDefinitionId() {
        return this.processDefinitionId;
    }

    /**
     * @param processDefinitionId
     *            null.
     */
    public void setProcessDefinitionId(String processDefinitionId) {
        this.processDefinitionId = processDefinitionId;
    }

    /** @return null. */
    public String getProcessDefinitionKey() {
        return this.processDefinitionKey;
    }

    /**
     * @param processDefinitionKey
     *            null.
     */
    public void setProcessDefinitionKey(String processDefinitionKey) {
        this.processDefinitionKey = processDefinitionKey;
    }

    /** @return null. */
    public Integer getProcessDefinitionVersion() {
        return this.processDefinitionVersion;
    }

    /**
     * @param processDefinitionVersion
     *            null.
     */
    public void setProcessDefinitionVersion(Integer processDefinitionVersion) {
        this.processDefinitionVersion = processDefinitionVersion;
    }

    /** @return . */
    public Set<BpmConfNode> getBpmConfNodes() {
        return this.bpmConfNodes;
    }

    /**
     * @param bpmConfNodes
     *            .
     */
    public void setBpmConfNodes(Set<BpmConfNode> bpmConfNodes) {
        this.bpmConfNodes = bpmConfNodes;
    }

    /** @return . */
    public Set<BpmProcess> getBpmProcesses() {
        return this.bpmProcesses;
    }

    /**
     * @param bpmProcesses
     *            .
     */
    public void setBpmProcesses(Set<BpmProcess> bpmProcesses) {
        this.bpmProcesses = bpmProcesses;
    }
}
