SET NAMES utf8;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
--  Table structure for `ACT_EVT_LOG`
-- ----------------------------
DROP TABLE IF EXISTS `ACT_EVT_LOG`;
CREATE TABLE `ACT_EVT_LOG` (
  `LOG_NR_` bigint(20) NOT NULL AUTO_INCREMENT,
  `TYPE_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `PROC_DEF_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `PROC_INST_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `EXECUTION_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `TASK_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `TIME_STAMP_` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `USER_ID_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `DATA_` longblob,
  `LOCK_OWNER_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `LOCK_TIME_` timestamp(3) NULL DEFAULT NULL,
  `IS_PROCESSED_` tinyint(4) DEFAULT '0',
  PRIMARY KEY (`LOG_NR_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Table structure for `ACT_GE_BYTEARRAY`
-- ----------------------------
DROP TABLE IF EXISTS `ACT_GE_BYTEARRAY`;
CREATE TABLE `ACT_GE_BYTEARRAY` (
  `ID_` varchar(64) COLLATE utf8_bin NOT NULL DEFAULT '',
  `REV_` int(11) DEFAULT NULL,
  `NAME_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `DEPLOYMENT_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `BYTES_` longblob,
  `GENERATED_` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`ID_`),
  KEY `ACT_FK_BYTEARR_DEPL` (`DEPLOYMENT_ID_`),
  CONSTRAINT `ACT_FK_BYTEARR_DEPL` FOREIGN KEY (`DEPLOYMENT_ID_`) REFERENCES `ACT_RE_DEPLOYMENT` (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Table structure for `ACT_GE_PROPERTY`
-- ----------------------------
DROP TABLE IF EXISTS `ACT_GE_PROPERTY`;
CREATE TABLE `ACT_GE_PROPERTY` (
  `NAME_` varchar(64) COLLATE utf8_bin NOT NULL DEFAULT '',
  `VALUE_` varchar(300) COLLATE utf8_bin DEFAULT NULL,
  `REV_` int(11) DEFAULT NULL,
  PRIMARY KEY (`NAME_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Table structure for `ACT_HI_ACTINST`
-- ----------------------------
DROP TABLE IF EXISTS `ACT_HI_ACTINST`;
CREATE TABLE `ACT_HI_ACTINST` (
  `ID_` varchar(64) COLLATE utf8_bin NOT NULL,
  `PROC_DEF_ID_` varchar(64) COLLATE utf8_bin NOT NULL,
  `PROC_INST_ID_` varchar(64) COLLATE utf8_bin NOT NULL,
  `EXECUTION_ID_` varchar(64) COLLATE utf8_bin NOT NULL,
  `ACT_ID_` varchar(255) COLLATE utf8_bin NOT NULL,
  `TASK_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `CALL_PROC_INST_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `ACT_NAME_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `ACT_TYPE_` varchar(255) COLLATE utf8_bin NOT NULL,
  `ASSIGNEE_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `START_TIME_` datetime(3) NOT NULL,
  `END_TIME_` datetime(3) DEFAULT NULL,
  `DURATION_` bigint(20) DEFAULT NULL,
  `TENANT_ID_` varchar(255) COLLATE utf8_bin DEFAULT '',
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_HI_ACT_INST_START` (`START_TIME_`),
  KEY `ACT_IDX_HI_ACT_INST_END` (`END_TIME_`),
  KEY `ACT_IDX_HI_ACT_INST_PROCINST` (`PROC_INST_ID_`,`ACT_ID_`),
  KEY `ACT_IDX_HI_ACT_INST_EXEC` (`EXECUTION_ID_`,`ACT_ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Table structure for `ACT_HI_ATTACHMENT`
-- ----------------------------
DROP TABLE IF EXISTS `ACT_HI_ATTACHMENT`;
CREATE TABLE `ACT_HI_ATTACHMENT` (
  `ID_` varchar(64) COLLATE utf8_bin NOT NULL,
  `REV_` int(11) DEFAULT NULL,
  `USER_ID_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `NAME_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `DESCRIPTION_` varchar(4000) COLLATE utf8_bin DEFAULT NULL,
  `TYPE_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `TASK_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `PROC_INST_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `URL_` varchar(4000) COLLATE utf8_bin DEFAULT NULL,
  `CONTENT_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Table structure for `ACT_HI_COMMENT`
-- ----------------------------
DROP TABLE IF EXISTS `ACT_HI_COMMENT`;
CREATE TABLE `ACT_HI_COMMENT` (
  `ID_` varchar(64) COLLATE utf8_bin NOT NULL,
  `TYPE_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `TIME_` datetime(3) NOT NULL,
  `USER_ID_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `TASK_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `PROC_INST_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `ACTION_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `MESSAGE_` varchar(4000) COLLATE utf8_bin DEFAULT NULL,
  `FULL_MSG_` longblob,
  PRIMARY KEY (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Table structure for `ACT_HI_DETAIL`
-- ----------------------------
DROP TABLE IF EXISTS `ACT_HI_DETAIL`;
CREATE TABLE `ACT_HI_DETAIL` (
  `ID_` varchar(64) COLLATE utf8_bin NOT NULL,
  `TYPE_` varchar(255) COLLATE utf8_bin NOT NULL,
  `PROC_INST_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `EXECUTION_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `TASK_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `ACT_INST_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `NAME_` varchar(255) COLLATE utf8_bin NOT NULL,
  `VAR_TYPE_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `REV_` int(11) DEFAULT NULL,
  `TIME_` datetime(3) NOT NULL,
  `BYTEARRAY_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `DOUBLE_` double DEFAULT NULL,
  `LONG_` bigint(20) DEFAULT NULL,
  `TEXT_` varchar(4000) COLLATE utf8_bin DEFAULT NULL,
  `TEXT2_` varchar(4000) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_HI_DETAIL_PROC_INST` (`PROC_INST_ID_`),
  KEY `ACT_IDX_HI_DETAIL_ACT_INST` (`ACT_INST_ID_`),
  KEY `ACT_IDX_HI_DETAIL_TIME` (`TIME_`),
  KEY `ACT_IDX_HI_DETAIL_NAME` (`NAME_`),
  KEY `ACT_IDX_HI_DETAIL_TASK_ID` (`TASK_ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Table structure for `ACT_HI_IDENTITYLINK`
-- ----------------------------
DROP TABLE IF EXISTS `ACT_HI_IDENTITYLINK`;
CREATE TABLE `ACT_HI_IDENTITYLINK` (
  `ID_` varchar(64) COLLATE utf8_bin NOT NULL DEFAULT '',
  `GROUP_ID_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `TYPE_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `USER_ID_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `TASK_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `PROC_INST_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_HI_IDENT_LNK_USER` (`USER_ID_`),
  KEY `ACT_IDX_HI_IDENT_LNK_TASK` (`TASK_ID_`),
  KEY `ACT_IDX_HI_IDENT_LNK_PROCINST` (`PROC_INST_ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Table structure for `ACT_HI_PROCINST`
-- ----------------------------
DROP TABLE IF EXISTS `ACT_HI_PROCINST`;
CREATE TABLE `ACT_HI_PROCINST` (
  `ID_` varchar(64) COLLATE utf8_bin NOT NULL,
  `PROC_INST_ID_` varchar(64) COLLATE utf8_bin NOT NULL,
  `BUSINESS_KEY_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PROC_DEF_ID_` varchar(64) COLLATE utf8_bin NOT NULL,
  `START_TIME_` datetime(3) NOT NULL,
  `END_TIME_` datetime(3) DEFAULT NULL,
  `DURATION_` bigint(20) DEFAULT NULL,
  `START_USER_ID_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `START_ACT_ID_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `END_ACT_ID_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `SUPER_PROCESS_INSTANCE_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `DELETE_REASON_` varchar(4000) COLLATE utf8_bin DEFAULT NULL,
  `TENANT_ID_` varchar(255) COLLATE utf8_bin DEFAULT '',
  `NAME_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID_`),
  UNIQUE KEY `PROC_INST_ID_` (`PROC_INST_ID_`),
  KEY `ACT_IDX_HI_PRO_INST_END` (`END_TIME_`),
  KEY `ACT_IDX_HI_PRO_I_BUSKEY` (`BUSINESS_KEY_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Table structure for `ACT_HI_TASKINST`
-- ----------------------------
DROP TABLE IF EXISTS `ACT_HI_TASKINST`;
CREATE TABLE `ACT_HI_TASKINST` (
  `ID_` varchar(64) COLLATE utf8_bin NOT NULL,
  `PROC_DEF_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `TASK_DEF_KEY_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PROC_INST_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `EXECUTION_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `NAME_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PARENT_TASK_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `DESCRIPTION_` varchar(4000) COLLATE utf8_bin DEFAULT NULL,
  `OWNER_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `ASSIGNEE_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `START_TIME_` datetime(3) NOT NULL,
  `CLAIM_TIME_` datetime(3) DEFAULT NULL,
  `END_TIME_` datetime(3) DEFAULT NULL,
  `DURATION_` bigint(20) DEFAULT NULL,
  `DELETE_REASON_` varchar(4000) COLLATE utf8_bin DEFAULT NULL,
  `PRIORITY_` int(11) DEFAULT NULL,
  `DUE_DATE_` datetime(3) DEFAULT NULL,
  `FORM_KEY_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `CATEGORY_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `TENANT_ID_` varchar(255) COLLATE utf8_bin DEFAULT '',
  PRIMARY KEY (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Table structure for `ACT_HI_VARINST`
-- ----------------------------
DROP TABLE IF EXISTS `ACT_HI_VARINST`;
CREATE TABLE `ACT_HI_VARINST` (
  `ID_` varchar(64) COLLATE utf8_bin NOT NULL,
  `PROC_INST_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `EXECUTION_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `TASK_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `NAME_` varchar(255) COLLATE utf8_bin NOT NULL,
  `VAR_TYPE_` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `REV_` int(11) DEFAULT NULL,
  `BYTEARRAY_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `DOUBLE_` double DEFAULT NULL,
  `LONG_` bigint(20) DEFAULT NULL,
  `TEXT_` varchar(4000) COLLATE utf8_bin DEFAULT NULL,
  `TEXT2_` varchar(4000) COLLATE utf8_bin DEFAULT NULL,
  `CREATE_TIME_` datetime(3) DEFAULT NULL,
  `LAST_UPDATED_TIME_` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_HI_PROCVAR_PROC_INST` (`PROC_INST_ID_`),
  KEY `ACT_IDX_HI_PROCVAR_NAME_TYPE` (`NAME_`,`VAR_TYPE_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Table structure for `ACT_ID_GROUP`
-- ----------------------------
DROP TABLE IF EXISTS `ACT_ID_GROUP`;
CREATE TABLE `ACT_ID_GROUP` (
  `ID_` varchar(64) COLLATE utf8_bin NOT NULL DEFAULT '',
  `REV_` int(11) DEFAULT NULL,
  `NAME_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `TYPE_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Table structure for `ACT_ID_INFO`
-- ----------------------------
DROP TABLE IF EXISTS `ACT_ID_INFO`;
CREATE TABLE `ACT_ID_INFO` (
  `ID_` varchar(64) COLLATE utf8_bin NOT NULL DEFAULT '',
  `REV_` int(11) DEFAULT NULL,
  `USER_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `TYPE_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `KEY_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `VALUE_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PASSWORD_` longblob,
  `PARENT_ID_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Table structure for `ACT_ID_MEMBERSHIP`
-- ----------------------------
DROP TABLE IF EXISTS `ACT_ID_MEMBERSHIP`;
CREATE TABLE `ACT_ID_MEMBERSHIP` (
  `USER_ID_` varchar(64) COLLATE utf8_bin NOT NULL DEFAULT '',
  `GROUP_ID_` varchar(64) COLLATE utf8_bin NOT NULL DEFAULT '',
  PRIMARY KEY (`USER_ID_`,`GROUP_ID_`),
  KEY `ACT_FK_MEMB_GROUP` (`GROUP_ID_`),
  CONSTRAINT `ACT_FK_MEMB_GROUP` FOREIGN KEY (`GROUP_ID_`) REFERENCES `ACT_ID_GROUP` (`ID_`),
  CONSTRAINT `ACT_FK_MEMB_USER` FOREIGN KEY (`USER_ID_`) REFERENCES `ACT_ID_USER` (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Table structure for `ACT_ID_USER`
-- ----------------------------
DROP TABLE IF EXISTS `ACT_ID_USER`;
CREATE TABLE `ACT_ID_USER` (
  `ID_` varchar(64) COLLATE utf8_bin NOT NULL DEFAULT '',
  `REV_` int(11) DEFAULT NULL,
  `FIRST_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `LAST_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `EMAIL_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PWD_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PICTURE_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Table structure for `ACT_RE_DEPLOYMENT`
-- ----------------------------
DROP TABLE IF EXISTS `ACT_RE_DEPLOYMENT`;
CREATE TABLE `ACT_RE_DEPLOYMENT` (
  `ID_` varchar(64) COLLATE utf8_bin NOT NULL DEFAULT '',
  `NAME_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `CATEGORY_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `TENANT_ID_` varchar(255) COLLATE utf8_bin DEFAULT '',
  `DEPLOY_TIME_` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Table structure for `ACT_RE_MODEL`
-- ----------------------------
DROP TABLE IF EXISTS `ACT_RE_MODEL`;
CREATE TABLE `ACT_RE_MODEL` (
  `ID_` varchar(64) COLLATE utf8_bin NOT NULL,
  `REV_` int(11) DEFAULT NULL,
  `NAME_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `KEY_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `CATEGORY_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `CREATE_TIME_` timestamp(3) NULL DEFAULT NULL,
  `LAST_UPDATE_TIME_` timestamp(3) NULL DEFAULT NULL,
  `VERSION_` int(11) DEFAULT NULL,
  `META_INFO_` varchar(4000) COLLATE utf8_bin DEFAULT NULL,
  `DEPLOYMENT_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `EDITOR_SOURCE_VALUE_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `EDITOR_SOURCE_EXTRA_VALUE_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `TENANT_ID_` varchar(255) COLLATE utf8_bin DEFAULT '',
  PRIMARY KEY (`ID_`),
  KEY `ACT_FK_MODEL_SOURCE` (`EDITOR_SOURCE_VALUE_ID_`),
  KEY `ACT_FK_MODEL_SOURCE_EXTRA` (`EDITOR_SOURCE_EXTRA_VALUE_ID_`),
  KEY `ACT_FK_MODEL_DEPLOYMENT` (`DEPLOYMENT_ID_`),
  CONSTRAINT `ACT_FK_MODEL_DEPLOYMENT` FOREIGN KEY (`DEPLOYMENT_ID_`) REFERENCES `ACT_RE_DEPLOYMENT` (`ID_`),
  CONSTRAINT `ACT_FK_MODEL_SOURCE` FOREIGN KEY (`EDITOR_SOURCE_VALUE_ID_`) REFERENCES `ACT_GE_BYTEARRAY` (`ID_`),
  CONSTRAINT `ACT_FK_MODEL_SOURCE_EXTRA` FOREIGN KEY (`EDITOR_SOURCE_EXTRA_VALUE_ID_`) REFERENCES `ACT_GE_BYTEARRAY` (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Table structure for `ACT_RE_PROCDEF`
-- ----------------------------
DROP TABLE IF EXISTS `ACT_RE_PROCDEF`;
CREATE TABLE `ACT_RE_PROCDEF` (
  `ID_` varchar(64) COLLATE utf8_bin NOT NULL,
  `REV_` int(11) DEFAULT NULL,
  `CATEGORY_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `NAME_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `KEY_` varchar(255) COLLATE utf8_bin NOT NULL,
  `VERSION_` int(11) NOT NULL,
  `DEPLOYMENT_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `RESOURCE_NAME_` varchar(4000) COLLATE utf8_bin DEFAULT NULL,
  `DGRM_RESOURCE_NAME_` varchar(4000) COLLATE utf8_bin DEFAULT NULL,
  `DESCRIPTION_` varchar(4000) COLLATE utf8_bin DEFAULT NULL,
  `HAS_START_FORM_KEY_` tinyint(4) DEFAULT NULL,
  `SUSPENSION_STATE_` int(11) DEFAULT NULL,
  `TENANT_ID_` varchar(255) COLLATE utf8_bin DEFAULT '',
  PRIMARY KEY (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Table structure for `ACT_RU_EVENT_SUBSCR`
-- ----------------------------
DROP TABLE IF EXISTS `ACT_RU_EVENT_SUBSCR`;
CREATE TABLE `ACT_RU_EVENT_SUBSCR` (
  `ID_` varchar(64) COLLATE utf8_bin NOT NULL,
  `REV_` int(11) DEFAULT NULL,
  `EVENT_TYPE_` varchar(255) COLLATE utf8_bin NOT NULL,
  `EVENT_NAME_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `EXECUTION_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `PROC_INST_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `ACTIVITY_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `CONFIGURATION_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `CREATED_` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `PROC_DEF_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `TENANT_ID_` varchar(255) COLLATE utf8_bin DEFAULT '',
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_EVENT_SUBSCR_CONFIG_` (`CONFIGURATION_`),
  KEY `ACT_FK_EVENT_EXEC` (`EXECUTION_ID_`),
  CONSTRAINT `ACT_FK_EVENT_EXEC` FOREIGN KEY (`EXECUTION_ID_`) REFERENCES `ACT_RU_EXECUTION` (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Table structure for `ACT_RU_EXECUTION`
-- ----------------------------
DROP TABLE IF EXISTS `ACT_RU_EXECUTION`;
CREATE TABLE `ACT_RU_EXECUTION` (
  `ID_` varchar(64) COLLATE utf8_bin NOT NULL DEFAULT '',
  `REV_` int(11) DEFAULT NULL,
  `PROC_INST_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `BUSINESS_KEY_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PARENT_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `PROC_DEF_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `SUPER_EXEC_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `ACT_ID_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `IS_ACTIVE_` tinyint(4) DEFAULT NULL,
  `IS_CONCURRENT_` tinyint(4) DEFAULT NULL,
  `IS_SCOPE_` tinyint(4) DEFAULT NULL,
  `IS_EVENT_SCOPE_` tinyint(4) DEFAULT NULL,
  `SUSPENSION_STATE_` int(11) DEFAULT NULL,
  `CACHED_ENT_STATE_` int(11) DEFAULT NULL,
  `TENANT_ID_` varchar(255) COLLATE utf8_bin DEFAULT '',
  `NAME_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_EXEC_BUSKEY` (`BUSINESS_KEY_`),
  KEY `ACT_FK_EXE_PARENT` (`PARENT_ID_`),
  KEY `ACT_FK_EXE_SUPER` (`SUPER_EXEC_`),
  KEY `ACT_FK_EXE_PROCDEF` (`PROC_DEF_ID_`),
  CONSTRAINT `ACT_FK_EXE_PARENT` FOREIGN KEY (`PARENT_ID_`) REFERENCES `ACT_RU_EXECUTION` (`ID_`),
  CONSTRAINT `ACT_FK_EXE_PROCDEF` FOREIGN KEY (`PROC_DEF_ID_`) REFERENCES `ACT_RE_PROCDEF` (`ID_`),
  CONSTRAINT `ACT_FK_EXE_SUPER` FOREIGN KEY (`SUPER_EXEC_`) REFERENCES `ACT_RU_EXECUTION` (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Table structure for `ACT_RU_IDENTITYLINK`
-- ----------------------------
DROP TABLE IF EXISTS `ACT_RU_IDENTITYLINK`;
CREATE TABLE `ACT_RU_IDENTITYLINK` (
  `ID_` varchar(64) COLLATE utf8_bin NOT NULL DEFAULT '',
  `REV_` int(11) DEFAULT NULL,
  `GROUP_ID_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `TYPE_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `USER_ID_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `TASK_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `PROC_INST_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `PROC_DEF_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_IDENT_LNK_USER` (`USER_ID_`),
  KEY `ACT_IDX_IDENT_LNK_GROUP` (`GROUP_ID_`),
  KEY `ACT_IDX_ATHRZ_PROCEDEF` (`PROC_DEF_ID_`),
  KEY `ACT_FK_TSKASS_TASK` (`TASK_ID_`),
  KEY `ACT_FK_IDL_PROCINST` (`PROC_INST_ID_`),
  CONSTRAINT `ACT_FK_ATHRZ_PROCEDEF` FOREIGN KEY (`PROC_DEF_ID_`) REFERENCES `ACT_RE_PROCDEF` (`ID_`),
  CONSTRAINT `ACT_FK_IDL_PROCINST` FOREIGN KEY (`PROC_INST_ID_`) REFERENCES `ACT_RU_EXECUTION` (`ID_`),
  CONSTRAINT `ACT_FK_TSKASS_TASK` FOREIGN KEY (`TASK_ID_`) REFERENCES `ACT_RU_TASK` (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Table structure for `ACT_RU_JOB`
-- ----------------------------
DROP TABLE IF EXISTS `ACT_RU_JOB`;
CREATE TABLE `ACT_RU_JOB` (
  `ID_` varchar(64) COLLATE utf8_bin NOT NULL,
  `REV_` int(11) DEFAULT NULL,
  `TYPE_` varchar(255) COLLATE utf8_bin NOT NULL,
  `LOCK_EXP_TIME_` timestamp(3) NULL DEFAULT NULL,
  `LOCK_OWNER_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `EXCLUSIVE_` tinyint(1) DEFAULT NULL,
  `EXECUTION_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `PROCESS_INSTANCE_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `PROC_DEF_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `RETRIES_` int(11) DEFAULT NULL,
  `EXCEPTION_STACK_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `EXCEPTION_MSG_` varchar(4000) COLLATE utf8_bin DEFAULT NULL,
  `DUEDATE_` timestamp(3) NULL DEFAULT NULL,
  `REPEAT_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `HANDLER_TYPE_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `HANDLER_CFG_` varchar(4000) COLLATE utf8_bin DEFAULT NULL,
  `TENANT_ID_` varchar(255) COLLATE utf8_bin DEFAULT '',
  PRIMARY KEY (`ID_`),
  KEY `ACT_FK_JOB_EXCEPTION` (`EXCEPTION_STACK_ID_`),
  CONSTRAINT `ACT_FK_JOB_EXCEPTION` FOREIGN KEY (`EXCEPTION_STACK_ID_`) REFERENCES `ACT_GE_BYTEARRAY` (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Table structure for `ACT_RU_TASK`
-- ----------------------------
DROP TABLE IF EXISTS `ACT_RU_TASK`;
CREATE TABLE `ACT_RU_TASK` (
  `ID_` varchar(64) COLLATE utf8_bin NOT NULL DEFAULT '',
  `REV_` int(11) DEFAULT NULL,
  `EXECUTION_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `PROC_INST_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `PROC_DEF_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `NAME_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `PARENT_TASK_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `DESCRIPTION_` varchar(4000) COLLATE utf8_bin DEFAULT NULL,
  `TASK_DEF_KEY_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `OWNER_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `ASSIGNEE_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `DELEGATION_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `PRIORITY_` int(11) DEFAULT NULL,
  `CREATE_TIME_` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `DUE_DATE_` datetime(3) DEFAULT NULL,
  `CATEGORY_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `SUSPENSION_STATE_` int(11) DEFAULT NULL,
  `TENANT_ID_` varchar(255) COLLATE utf8_bin DEFAULT '',
  `FORM_KEY_` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_TASK_CREATE` (`CREATE_TIME_`),
  KEY `ACT_FK_TASK_EXE` (`EXECUTION_ID_`),
  KEY `ACT_FK_TASK_PROCINST` (`PROC_INST_ID_`),
  KEY `ACT_FK_TASK_PROCDEF` (`PROC_DEF_ID_`),
  CONSTRAINT `ACT_FK_TASK_EXE` FOREIGN KEY (`EXECUTION_ID_`) REFERENCES `ACT_RU_EXECUTION` (`ID_`),
  CONSTRAINT `ACT_FK_TASK_PROCDEF` FOREIGN KEY (`PROC_DEF_ID_`) REFERENCES `ACT_RE_PROCDEF` (`ID_`),
  CONSTRAINT `ACT_FK_TASK_PROCINST` FOREIGN KEY (`PROC_INST_ID_`) REFERENCES `ACT_RU_EXECUTION` (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Table structure for `ACT_RU_VARIABLE`
-- ----------------------------
DROP TABLE IF EXISTS `ACT_RU_VARIABLE`;
CREATE TABLE `ACT_RU_VARIABLE` (
  `ID_` varchar(64) COLLATE utf8_bin NOT NULL,
  `REV_` int(11) DEFAULT NULL,
  `TYPE_` varchar(255) COLLATE utf8_bin NOT NULL,
  `NAME_` varchar(255) COLLATE utf8_bin NOT NULL,
  `EXECUTION_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `PROC_INST_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `TASK_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `BYTEARRAY_ID_` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `DOUBLE_` double DEFAULT NULL,
  `LONG_` bigint(20) DEFAULT NULL,
  `TEXT_` varchar(4000) COLLATE utf8_bin DEFAULT NULL,
  `TEXT2_` varchar(4000) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_VARIABLE_TASK_ID` (`TASK_ID_`),
  KEY `ACT_FK_VAR_EXE` (`EXECUTION_ID_`),
  KEY `ACT_FK_VAR_PROCINST` (`PROC_INST_ID_`),
  KEY `ACT_FK_VAR_BYTEARRAY` (`BYTEARRAY_ID_`),
  CONSTRAINT `ACT_FK_VAR_BYTEARRAY` FOREIGN KEY (`BYTEARRAY_ID_`) REFERENCES `ACT_GE_BYTEARRAY` (`ID_`),
  CONSTRAINT `ACT_FK_VAR_EXE` FOREIGN KEY (`EXECUTION_ID_`) REFERENCES `ACT_RU_EXECUTION` (`ID_`),
  CONSTRAINT `ACT_FK_VAR_PROCINST` FOREIGN KEY (`PROC_INST_ID_`) REFERENCES `ACT_RU_EXECUTION` (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Table structure for `BPM_CATEGORY`
-- ----------------------------
DROP TABLE IF EXISTS `BPM_CATEGORY`;
CREATE TABLE `BPM_CATEGORY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(200) DEFAULT NULL,
  `PRIORITY` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `BPM_CONF_BASE`
-- ----------------------------
DROP TABLE IF EXISTS `BPM_CONF_BASE`;
CREATE TABLE `BPM_CONF_BASE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PROCESS_DEFINITION_ID` varchar(200) DEFAULT NULL,
  `PROCESS_DEFINITION_NAME` varchar(200) DEFAULT NULL,
  `PROCESS_DEFINITION_KEY` varchar(200) DEFAULT NULL,
  `PROCESS_DEFINITION_VERSION` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `BPM_CONF_COUNTERSIGN`
-- ----------------------------
DROP TABLE IF EXISTS `BPM_CONF_COUNTERSIGN`;
CREATE TABLE `BPM_CONF_COUNTERSIGN` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SEQUENTIAL` int(11) DEFAULT NULL,
  `PARTICIPANT` varchar(200) DEFAULT NULL,
  `TYPE` int(11) DEFAULT NULL,
  `RATE` int(11) DEFAULT NULL,
  `NODE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_BPM_CONF_COUNTERSIGN_NODE` (`NODE_ID`),
  CONSTRAINT `FK_BPM_CONF_COUNTERSIGN_NODE` FOREIGN KEY (`NODE_ID`) REFERENCES `BPM_CONF_NODE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `BPM_CONF_FORM`
-- ----------------------------
DROP TABLE IF EXISTS `BPM_CONF_FORM`;
CREATE TABLE `BPM_CONF_FORM` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `FORM_ID` bigint(20) DEFAULT NULL,
  `VALUE` varchar(200) DEFAULT NULL,
  `TYPE` int(11) DEFAULT NULL,
  `ORIGIN_VALUE` varchar(200) DEFAULT NULL,
  `ORIGIN_TYPE` int(11) DEFAULT NULL,
  `STATUS` int(11) DEFAULT NULL,
  `NODE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_BPM_CONF_FORM_NODE` (`NODE_ID`),
  CONSTRAINT `FK_BPM_CONF_FORM_NODE` FOREIGN KEY (`NODE_ID`) REFERENCES `BPM_CONF_NODE` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `BPM_CONF_LISTENER`
-- ----------------------------
DROP TABLE IF EXISTS `BPM_CONF_LISTENER`;
CREATE TABLE `BPM_CONF_LISTENER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(200) DEFAULT NULL,
  `TYPE` int(11) DEFAULT NULL,
  `STATUS` int(11) DEFAULT NULL,
  `PRIORITY` int(11) DEFAULT NULL,
  `NODE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_BPM_CONF_LISTENER_NODE` (`NODE_ID`),
  CONSTRAINT `FK_BPM_CONF_LISTENER_NODE` FOREIGN KEY (`NODE_ID`) REFERENCES `BPM_CONF_NODE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `BPM_CONF_NODE`
-- ----------------------------
DROP TABLE IF EXISTS `BPM_CONF_NODE`;
CREATE TABLE `BPM_CONF_NODE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CODE` varchar(200) DEFAULT NULL,
  `NAME` varchar(200) DEFAULT NULL,
  `TYPE` varchar(200) DEFAULT NULL,
  `CONF_USER` int(11) DEFAULT NULL,
  `CONF_LISTENER` int(11) DEFAULT NULL,
  `CONF_RULE` int(11) DEFAULT NULL,
  `CONF_FORM` int(11) DEFAULT NULL,
  `CONF_OPERATION` int(11) DEFAULT NULL,
  `CONF_NOTICE` int(11) DEFAULT NULL,
  `PRIORITY` int(11) DEFAULT NULL,
  `CONF_BASE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_BPM_CONF_NODE_CONF_BASE` (`CONF_BASE_ID`),
  CONSTRAINT `FK_BPM_CONF_NODE_CONF_BASE` FOREIGN KEY (`CONF_BASE_ID`) REFERENCES `BPM_CONF_BASE` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=160 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `BPM_CONF_NOTICE`
-- ----------------------------
DROP TABLE IF EXISTS `BPM_CONF_NOTICE`;
CREATE TABLE `BPM_CONF_NOTICE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TYPE` int(11) DEFAULT NULL,
  `RECEIVER` varchar(200) DEFAULT NULL,
  `DUE_DATE` varchar(50) DEFAULT NULL,
  `NODE_ID` bigint(20) DEFAULT NULL,
  `TEMPLATE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_BPM_CONF_NOTICE_NODE` (`NODE_ID`),
  KEY `FK_BPM_CONF_NOTICE_TEMPLATE` (`TEMPLATE_ID`),
  CONSTRAINT `FK_BPM_CONF_NOTICE_NODE` FOREIGN KEY (`NODE_ID`) REFERENCES `BPM_CONF_NODE` (`ID`),
  CONSTRAINT `FK_BPM_CONF_NOTICE_TEMPLATE` FOREIGN KEY (`TEMPLATE_ID`) REFERENCES `BPM_MAIL_TEMPLATE` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `BPM_CONF_OPERATION`
-- ----------------------------
DROP TABLE IF EXISTS `BPM_CONF_OPERATION`;
CREATE TABLE `BPM_CONF_OPERATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(200) DEFAULT NULL,
  `PRIORITY` int(11) DEFAULT NULL,
  `NODE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_BPM_CONF_OPERATION_NODE` (`NODE_ID`),
  CONSTRAINT `FK_BPM_CONF_OPERATION_NODE` FOREIGN KEY (`NODE_ID`) REFERENCES `BPM_CONF_NODE` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `BPM_CONF_RULE`
-- ----------------------------
DROP TABLE IF EXISTS `BPM_CONF_RULE`;
CREATE TABLE `BPM_CONF_RULE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(200) DEFAULT NULL,
  `NODE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_BPM_CONF_RULE_NODE` (`NODE_ID`),
  CONSTRAINT `FK_BPM_CONF_RULE_NODE` FOREIGN KEY (`NODE_ID`) REFERENCES `BPM_CONF_NODE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `BPM_CONF_USER`
-- ----------------------------
DROP TABLE IF EXISTS `BPM_CONF_USER`;
CREATE TABLE `BPM_CONF_USER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` varchar(200) DEFAULT NULL,
  `SHOW_VALUE` varchar(500) DEFAULT NULL,
  `TYPE` int(11) DEFAULT NULL,
  `STATUS` int(11) DEFAULT NULL,
  `PRIORITY` int(11) DEFAULT NULL,
  `NODE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_BPM_CONF_USER_NODE` (`NODE_ID`),
  CONSTRAINT `FK_BPM_CONF_USER_NODE` FOREIGN KEY (`NODE_ID`) REFERENCES `BPM_CONF_NODE` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=44 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `BPM_DELEGATE_HISTORY`
-- ----------------------------
DROP TABLE IF EXISTS `BPM_DELEGATE_HISTORY`;
CREATE TABLE `BPM_DELEGATE_HISTORY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ASSIGNEE` varchar(200) DEFAULT NULL,
  `ATTORNEY` varchar(200) DEFAULT NULL,
  `DELEGATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `TASK_ID` varchar(100) DEFAULT NULL,
  `STATUS` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `BPM_DELEGATE_INFO`
-- ----------------------------
DROP TABLE IF EXISTS `BPM_DELEGATE_INFO`;
CREATE TABLE `BPM_DELEGATE_INFO` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ASSIGNEE` varchar(200) DEFAULT NULL,
  `ATTORNEY_TYPE` varchar(1) DEFAULT NULL COMMENT '1-USER 2-USERGROUP',
  `ATTORNEY` varchar(200) DEFAULT NULL,
  `START_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `END_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `PROCESS_DEFINITION_ID` varchar(100) DEFAULT NULL,
  `STATUS` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `BPM_MAIL_TEMPLATE`
-- ----------------------------
DROP TABLE IF EXISTS `BPM_MAIL_TEMPLATE`;
CREATE TABLE `BPM_MAIL_TEMPLATE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(50) DEFAULT NULL,
  `SUBJECT` varchar(100) DEFAULT NULL,
  `CONTENT` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `BPM_PROCESS`
-- ----------------------------
DROP TABLE IF EXISTS `BPM_PROCESS`;
CREATE TABLE `BPM_PROCESS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(200) DEFAULT NULL,
  `CATEGORY_ID` bigint(20) DEFAULT NULL,
  `PRIORITY` int(11) DEFAULT NULL,
  `DESCN` varchar(200) DEFAULT NULL,
  `USE_TASK_CONF` int(11) DEFAULT NULL,
  `CODE` varchar(64) DEFAULT NULL,
  `CONF_BASE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_BPM_PROCESS_CATEGORY_ID` (`CATEGORY_ID`),
  KEY `FK_BPM_PROCESS_CONF_BASE` (`CONF_BASE_ID`),
  CONSTRAINT `FK_BPM_PROCESS_CATEGORY_ID` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `BPM_CATEGORY` (`ID`),
  CONSTRAINT `FK_BPM_PROCESS_CONF_BASE` FOREIGN KEY (`CONF_BASE_ID`) REFERENCES `BPM_CONF_BASE` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `BPM_TASK_BUSSINESS`
-- ----------------------------
DROP TABLE IF EXISTS `BPM_TASK_BUSSINESS`;
CREATE TABLE `BPM_TASK_BUSSINESS` (
  `TASK_ID` varchar(100) NOT NULL,
  `TASK_NAME` varchar(100) NOT NULL,
  `TABLE_NAME` varchar(100) NOT NULL,
  `BUSSI_ID` bigint(20) NOT NULL,
  `PROCESSINST_ID` varchar(100) NOT NULL,
  `BUSSI_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`TASK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `BPM_TASK_CONF`
-- ----------------------------
DROP TABLE IF EXISTS `BPM_TASK_CONF`;
CREATE TABLE `BPM_TASK_CONF` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `BUSINESS_KEY` varchar(200) DEFAULT NULL,
  `TASK_DEFINITION_KEY` varchar(200) DEFAULT NULL,
  `ASSIGNEE` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `BPM_TASK_DEF`
-- ----------------------------
DROP TABLE IF EXISTS `BPM_TASK_DEF`;
CREATE TABLE `BPM_TASK_DEF` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TASK_DEFINITION_KEY` varchar(200) DEFAULT NULL,
  `ASSIGNEE` varchar(200) DEFAULT NULL,
  `CANDIDATE` varchar(200) DEFAULT NULL,
  `PROCESS_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_BPM_TASK_DEF_ID` (`PROCESS_ID`),
  CONSTRAINT `FK_BPM_TASK_DEF_ID` FOREIGN KEY (`PROCESS_ID`) REFERENCES `BPM_PROCESS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `BPM_TASK_DEF_NOTICE`
-- ----------------------------
DROP TABLE IF EXISTS `BPM_TASK_DEF_NOTICE`;
CREATE TABLE `BPM_TASK_DEF_NOTICE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TASK_DEFINITION_KEY` varchar(200) DEFAULT NULL,
  `TYPE` int(11) DEFAULT NULL,
  `RECEIVER` varchar(200) DEFAULT NULL,
  `DUE_DATE` varchar(50) DEFAULT NULL,
  `TEMPLATE_ID` bigint(20) DEFAULT NULL,
  `PROCESS_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_BPM_TASK_DEF_NOTICE_PROCESS` (`PROCESS_ID`),
  KEY `FK_BPM_TASK_DEF_NOTICE_TEMPLATE` (`TEMPLATE_ID`),
  CONSTRAINT `FK_BPM_TASK_DEF_NOTICE_PROCESS` FOREIGN KEY (`PROCESS_ID`) REFERENCES `BPM_PROCESS` (`ID`),
  CONSTRAINT `FK_BPM_TASK_DEF_NOTICE_TEMPLATE` FOREIGN KEY (`TEMPLATE_ID`) REFERENCES `BPM_MAIL_TEMPLATE` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `FORM_TEMPLATE`
-- ----------------------------
DROP TABLE IF EXISTS `FORM_TEMPLATE`;
CREATE TABLE `FORM_TEMPLATE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TYPE` int(11) DEFAULT NULL,
  `NAME` varchar(200) DEFAULT NULL,
  `content` text,
  `code` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `maintain_extkeyvalue`
-- ----------------------------
DROP TABLE IF EXISTS `MAINTAIN_EXTKEYVALUE`;
CREATE TABLE `MAINTAIN_EXTKEYVALUE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `EXTKEYVALUECATEGORY_ID` bigint(20) unsigned DEFAULT NULL,
  `NAME` varchar(200) DEFAULT NULL,
  `VALUE` varchar(200) DEFAULT NULL,
  `IS_SHOW` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `KEYVALUETYPE_ID` (`EXTKEYVALUECATEGORY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=50 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `maintain_extkeyvalue_category`
-- ----------------------------
DROP TABLE IF EXISTS `MAINTAIN_EXTKEYVALUE_CATEGORY`;
CREATE TABLE `MAINTAIN_EXTKEYVALUE_CATEGORY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) DEFAULT NULL,
  `TYPE` varchar(50) DEFAULT NULL,
  `IS_SHOW` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `maintain_icon`
-- ----------------------------
DROP TABLE IF EXISTS `MAINTAIN_ICON`;
CREATE TABLE `MAINTAIN_ICON` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `IDENTITY` varchar(100) DEFAULT NULL,
  `CSS_CLASS` varchar(100) DEFAULT NULL,
  `IMG_SRC` varchar(200) DEFAULT NULL,
  `WIDTH` smallint(6) DEFAULT NULL,
  `HEIGHT` smallint(6) DEFAULT NULL,
  `SPRITE_SRC` varchar(200) DEFAULT NULL,
  `LEFT` smallint(6) DEFAULT NULL,
  `TOP` smallint(6) DEFAULT NULL,
  `STYLE` varchar(100) DEFAULT NULL,
  `TYPE` varchar(30) DEFAULT NULL,
  `DESCRIPTION` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_MAINTAIN_ICON_IDENTITY` (`IDENTITY`)
) ENGINE=InnoDB AUTO_INCREMENT=1516 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `maintain_map`
-- ----------------------------
DROP TABLE IF EXISTS `MAINTAIN_MAP`;
CREATE TABLE `MAINTAIN_MAP` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MAP_KEY` varchar(200) DEFAULT NULL,
  `MAP_VALUE` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_MAINTAIN_MAP_KEY` (`MAP_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `maintain_notification_data`
-- ----------------------------
DROP TABLE IF EXISTS `MAINTAIN_NOTIFICATION_DATA`;
CREATE TABLE `MAINTAIN_NOTIFICATION_DATA` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint(20) DEFAULT NULL,
  `SYSTEM` varchar(50) DEFAULT NULL,
  `TITLE` varchar(600) DEFAULT NULL,
  `CONTENT` varchar(2000) DEFAULT NULL,
  `DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `IS_READ` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_MAINTAIN_NOTIFICATION_DATA_USER_ID_READ` (`USER_ID`,`IS_READ`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `maintain_notification_template`
-- ----------------------------
DROP TABLE IF EXISTS `MAINTAIN_NOTIFICATION_TEMPLATE`;
CREATE TABLE `MAINTAIN_NOTIFICATION_TEMPLATE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(200) DEFAULT NULL,
  `SYSTEM` varchar(50) DEFAULT NULL,
  `TITLE` varchar(600) DEFAULT NULL,
  `TEMPLATE` varchar(2000) DEFAULT NULL,
  `DELETED` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_MAINTAIN_NOTIFICATION_TEMPLATE_NAME` (`NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `maintain_task_definition`
-- ----------------------------
DROP TABLE IF EXISTS `MAINTAIN_TASK_DEFINITION`;
CREATE TABLE `MAINTAIN_TASK_DEFINITION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(500) DEFAULT NULL,
  `CRON` varchar(200) DEFAULT NULL,
  `BEAN_CLASS` varchar(200) DEFAULT NULL,
  `BEAN_NAME` varchar(200) DEFAULT NULL,
  `METHOD_NAME` varchar(200) DEFAULT NULL,
  `IS_START` tinyint(1) DEFAULT NULL,
  `DESCRIPTION` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `personal_calendar`
-- ----------------------------
DROP TABLE IF EXISTS `PERSONAL_CALENDAR`;
CREATE TABLE `PERSONAL_CALENDAR` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint(20) DEFAULT NULL,
  `TITLE` varchar(500) COLLATE utf8_bin DEFAULT NULL,
  `DETAILS` varchar(1000) COLLATE utf8_bin DEFAULT NULL,
  `START_DATE` date DEFAULT NULL,
  `LENGTH` int(11) DEFAULT NULL,
  `START_TIME` time DEFAULT NULL,
  `END_TIME` time DEFAULT NULL,
  `BACKGROUND_COLOR` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `TEXT_COLOR` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `OFFICE_CALENDAR_USER_ID_START_DATE` (`USER_ID`,`START_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ----------------------------
--  Table structure for `personal_message`
-- ----------------------------
DROP TABLE IF EXISTS `PERSONAL_MESSAGE`;
CREATE TABLE `PERSONAL_MESSAGE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SENDER_ID` bigint(20) DEFAULT NULL,
  `RECEIVER_ID` bigint(20) DEFAULT NULL,
  `SEND_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `TITLE` varchar(200) DEFAULT NULL,
  `SENDER_STATE` varchar(20) DEFAULT NULL,
  `SENDER_STATE_CHANGE_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `RECEIVER_STATE` varchar(20) DEFAULT NULL,
  `RECEIVER_STATE_CHANGE_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `TYPE` varchar(20) DEFAULT NULL,
  `IS_READ` tinyint(1) DEFAULT NULL,
  `IS_REPLIED` tinyint(1) DEFAULT NULL,
  `PARENT_ID` bigint(20) DEFAULT NULL,
  `PARENT_IDS` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_PERSONAL_MESSAGE_SENDER_ID_SENDER_STATE` (`SENDER_ID`,`SENDER_STATE`),
  KEY `IDX_PERSONAL_MESSAGE_RECEIVER_ID_RECEIVER_STATE` (`RECEIVER_ID`,`RECEIVER_STATE`,`IS_READ`),
  KEY `IDX_PERSONAL_SENDER_STATE_CHANGE_DATE` (`SENDER_STATE_CHANGE_DATE`),
  KEY `IDX_PERSONAL_RECEIVER_STATE_CHANGE_DATE` (`RECEIVER_STATE_CHANGE_DATE`),
  KEY `IDX_PERSONAL_PARENT_ID` (`PARENT_ID`),
  KEY `IDX_PERSONAL_PARENT_IDS` (`PARENT_IDS`),
  KEY `IDX_PERSONAL_MESSAGE_TYPE` (`TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `personal_message_content`
-- ----------------------------
DROP TABLE IF EXISTS `PERSONAL_MESSAGE_CONTENT`;
CREATE TABLE `PERSONAL_MESSAGE_CONTENT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MESSAGE_ID` bigint(20) DEFAULT NULL,
  `CONTENT` longtext,
  PRIMARY KEY (`ID`),
  KEY `IDX_PERSONAL_MESSAGE_CONTENT_MESSAGE_ID` (`MESSAGE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `sys_auth`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_AUTH`;
CREATE TABLE `SYS_AUTH` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ORGANIZATION_ID` bigint(20) DEFAULT NULL,
  `JOB_ID` bigint(20) DEFAULT NULL,
  `USER_ID` bigint(20) DEFAULT NULL,
  `GROUP_ID` bigint(20) DEFAULT NULL,
  `ROLE_IDS` varchar(500) DEFAULT NULL,
  `TYPE` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_SYS_AUTH_ORGANIZATION` (`ORGANIZATION_ID`),
  KEY `IDX_SYS_AUTH_JOB` (`JOB_ID`),
  KEY `IDX_SYS_AUTH_USER` (`USER_ID`),
  KEY `IDX_SYS_AUTH_GROUP` (`GROUP_ID`),
  KEY `IDX_SYS_AUTH_TYPE` (`TYPE`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `sys_group`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_GROUP`;
CREATE TABLE `SYS_GROUP` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) DEFAULT NULL,
  `TYPE` varchar(50) DEFAULT NULL,
  `IS_SHOW` tinyint(1) DEFAULT NULL,
  `DEFAULT_GROUP` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_SYS_GROUP_TYPE` (`TYPE`),
  KEY `IDX_SYS_GROUP_SHOW` (`IS_SHOW`),
  KEY `IDX_SYS_GROUP_DEFAULT_GROUP` (`DEFAULT_GROUP`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `sys_group_relation`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_GROUP_RELATION`;
CREATE TABLE `SYS_GROUP_RELATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `GROUP_ID` bigint(20) DEFAULT NULL,
  `ORGANIZATION_ID` bigint(20) DEFAULT NULL,
  `USER_ID` bigint(20) DEFAULT NULL,
  `START_USER_ID` bigint(20) DEFAULT NULL,
  `END_USER_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_SYS_GROUP_RELATION_GROUP` (`GROUP_ID`),
  KEY `IDX_SYS_GROUP_RELATION_ORGANIZATION` (`ORGANIZATION_ID`),
  KEY `IDX_SYS_GROUP_RELATION_USER` (`USER_ID`),
  KEY `IDX_SYS_GROUP_RELATION_START_USER_ID` (`START_USER_ID`),
  KEY `IDX_SYS_GROUP_RELATION_END_USER_ID` (`END_USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `sys_job`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_JOB`;
CREATE TABLE `SYS_JOB` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) DEFAULT NULL,
  `PARENT_ID` bigint(20) DEFAULT NULL,
  `PARENT_IDS` varchar(200) DEFAULT '',
  `ICON` varchar(200) DEFAULT NULL,
  `WEIGHT` int(11) DEFAULT NULL,
  `IS_SHOW` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_SYS_JOB_NAM` (`NAME`),
  KEY `IDX_SYS_JOB_PARENT_ID` (`PARENT_ID`),
  KEY `IDX_SYS_JOB_PARENT_IDS_WEIGHT` (`PARENT_IDS`,`WEIGHT`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `sys_organization`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_ORGANIZATION`;
CREATE TABLE `SYS_ORGANIZATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) DEFAULT NULL,
  `TYPE` varchar(20) DEFAULT NULL,
  `PARENT_ID` bigint(20) DEFAULT NULL,
  `PARENT_IDS` varchar(200) DEFAULT '',
  `ICON` varchar(200) DEFAULT NULL,
  `WEIGHT` int(11) DEFAULT NULL,
  `IS_SHOW` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_SYS_ORGANIZATION_NAME` (`NAME`),
  KEY `IDX_SYS_ORGANIZATION_TYPE` (`TYPE`),
  KEY `IDX_SYS_ORGANIZATION_PARENT_ID` (`PARENT_ID`),
  KEY `IDX_SYS_ORGANIZATION_PARENT_IDS_WEIGHT` (`PARENT_IDS`,`WEIGHT`)
) ENGINE=InnoDB AUTO_INCREMENT=1003 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `sys_permission`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_PERMISSION`;
CREATE TABLE `SYS_PERMISSION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) DEFAULT NULL,
  `PERMISSION` varchar(100) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `IS_SHOW` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_SYS_PERMISSION_NAME` (`NAME`),
  KEY `IDX_SYS_PERMISSION_PERMISSION` (`PERMISSION`),
  KEY `IDX_SYS_PERMISSION_SHOW` (`IS_SHOW`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `sys_resource`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_RESOURCE`;
CREATE TABLE `SYS_RESOURCE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) DEFAULT NULL,
  `IDENTITY` varchar(100) DEFAULT NULL,
  `URL` varchar(200) DEFAULT NULL,
  `PARENT_ID` bigint(20) DEFAULT NULL,
  `PARENT_IDS` varchar(200) DEFAULT '',
  `ICON` varchar(200) DEFAULT NULL,
  `WEIGHT` int(11) DEFAULT NULL,
  `IS_SHOW` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_SYS_RESOURCE_NAME` (`NAME`),
  KEY `IDX_SYS_RESOURCE_IDENTITY` (`IDENTITY`),
  KEY `IDX_SYS_RESOURCE_USER` (`URL`),
  KEY `IDX_SYS_RESOURCE_PARENT_ID` (`PARENT_ID`),
  KEY `IDX_SYS_RESOURCE_PARENT_IDS_WEIGHT` (`PARENT_IDS`,`WEIGHT`)
) ENGINE=InnoDB AUTO_INCREMENT=91 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `sys_role`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_ROLE`;
CREATE TABLE `SYS_ROLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) DEFAULT NULL,
  `ROLE` varchar(100) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `IS_SHOW` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_SYS_ROLE_NAME` (`NAME`),
  KEY `IDX_SYS_ROLE_ROLE` (`ROLE`),
  KEY `IDX_SYS_ROLE_SHOW` (`IS_SHOW`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `sys_role_resource_permission`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_ROLE_RESOURCE_PERMISSION`;
CREATE TABLE `SYS_ROLE_RESOURCE_PERMISSION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ROLE_ID` bigint(20) DEFAULT NULL,
  `RESOURCE_ID` bigint(20) DEFAULT NULL,
  `PERMISSION_IDS` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_SYS_ROLE_RESOURCE_PERMISSION` (`ROLE_ID`,`RESOURCE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=38 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `sys_user`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_USER`;
CREATE TABLE `SYS_USER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(100) DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `MOBILE_PHONE_NUMBER` varchar(20) DEFAULT NULL,
  `PASSWORD` varchar(100) DEFAULT NULL,
  `SALT` varchar(10) DEFAULT NULL,
  `CREATE_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `STATUS` varchar(50) DEFAULT NULL,
  `DELETED` tinyint(1) DEFAULT NULL,
  `ADMIN` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_SYS_USER_USERNAME` (`USERNAME`),
  UNIQUE KEY `UNIQUE_SYS_USER_EMAIL` (`EMAIL`),
  UNIQUE KEY `UNIQUE_SYS_USER_MOBILE_PHONE_NUMBER` (`MOBILE_PHONE_NUMBER`),
  KEY `IDX_SYS_USER_STATUS` (`STATUS`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `sys_user_last_online`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_USER_LAST_ONLINE`;
CREATE TABLE `SYS_USER_LAST_ONLINE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint(20) DEFAULT NULL,
  `USERNAME` varchar(100) DEFAULT NULL,
  `UID` varchar(100) DEFAULT NULL,
  `HOST` varchar(100) DEFAULT NULL,
  `USER_AGENT` varchar(200) DEFAULT NULL,
  `SYSTEM_HOST` varchar(100) DEFAULT NULL,
  `LAST_LOGIN_TIMESTAMP` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_STOP_TIMESTAMP` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LOGIN_COUNT` bigint(20) DEFAULT NULL,
  `TOTAL_ONLINE_TIME` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_SYS_USER_LAST_ONLINE_SYS_USER_ID` (`USER_ID`),
  KEY `IDX_SYS_USER_LAST_ONLINE_USERNAME` (`USERNAME`),
  KEY `IDX_SYS_USER_LAST_ONLINE_HOST` (`HOST`),
  KEY `IDX_SYS_USER_LAST_ONLINE_SYSTEM_HOST` (`SYSTEM_HOST`),
  KEY `IDX_SYS_USER_LAST_ONLINE_LAST_LOGIN_TIMESTAMP` (`LAST_LOGIN_TIMESTAMP`),
  KEY `IDX_SYS_USER_LAST_ONLINE_LAST_STOP_TIMESTAMP` (`LAST_STOP_TIMESTAMP`),
  KEY `IDX_SYS_USER_LAST_ONLINE_USER_AGENT` (`USER_AGENT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `sys_user_online`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_USER_ONLINE`;
CREATE TABLE `SYS_USER_ONLINE` (
  `ID` varchar(100) NOT NULL,
  `USER_ID` bigint(20) DEFAULT '0',
  `USERNAME` varchar(100) DEFAULT NULL,
  `HOST` varchar(100) DEFAULT NULL,
  `SYSTEM_HOST` varchar(100) DEFAULT NULL,
  `USER_AGENT` varchar(200) DEFAULT NULL,
  `STATUS` varchar(50) DEFAULT NULL,
  `START_TIMESTSAMP` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LAST_ACCESS_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `TIMEOUT` bigint(20) DEFAULT NULL,
  `SESSION` mediumtext,
  PRIMARY KEY (`ID`),
  KEY `IDX_SYS_USER_ONLINE_SYS_USER_ID` (`USER_ID`),
  KEY `IDX_SYS_USER_ONLINE_USERNAME` (`USERNAME`),
  KEY `IDX_SYS_USER_ONLINE_HOST` (`HOST`),
  KEY `IDX_SYS_USER_ONLINE_SYSTEM_HOST` (`SYSTEM_HOST`),
  KEY `IDX_SYS_USER_ONLINE_START_TIMESTSAMP` (`START_TIMESTSAMP`),
  KEY `IDX_SYS_USER_ONLINE_LAST_ACCESS_TIME` (`LAST_ACCESS_TIME`),
  KEY `IDX_SYS_USER_ONLINE_USER_AGENT` (`USER_AGENT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `sys_user_organization_job`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_USER_ORGANIZATION_JOB`;
CREATE TABLE `SYS_USER_ORGANIZATION_JOB` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint(20) DEFAULT NULL,
  `ORGANIZATION_ID` bigint(20) DEFAULT NULL,
  `JOB_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_SYS_USER_ORGANIZATION_JOB` (`USER_ID`,`ORGANIZATION_ID`,`JOB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Table structure for `sys_user_status_history`
-- ----------------------------
DROP TABLE IF EXISTS `SYS_USER_STATUS_HISTORY`;
CREATE TABLE `SYS_USER_STATUS_HISTORY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint(20) DEFAULT NULL,
  `STATUS` varchar(50) DEFAULT NULL,
  `REASON` varchar(200) DEFAULT NULL,
  `OP_USER_ID` bigint(20) DEFAULT NULL,
  `OP_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ID`),
  KEY `IDX_SYS_USER_BLOCK_HISTORY_USER_ID_BLOCK_DATE` (`USER_ID`,`OP_DATE`),
  KEY `IDX_SYS_USER_BLOCK_HISTORY_OP_USER_ID_OP_DATE` (`OP_USER_ID`,`OP_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

SET FOREIGN_KEY_CHECKS = 1;
