package com.luna.bpm.process.entity;

// Generated by Hibernate Tools
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.luna.common.entity.BaseEntity;

/**
 * BpmDelegateInfo .
 * 
 * @author Lingo
 */
@Entity
@Table(name = "BPM_DELEGATE_INFO")
public class BpmDelegateInfo extends BaseEntity<Long> {
    private static final long serialVersionUID = 0L;

    @Column(name = "ASSIGNEE", length = 200)
    private String assignee;

    @Column(name = "ATTORNEY", length = 200)
    private String attorney;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "START_TIME", length = 26)
    private Date startTime;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "END_TIME", length = 26)
    private Date endTime;

    @Column(name = "PROCESS_DEFINITION_ID", length = 100)
    private String processDefinitionId;

    @Column(name = "STATUS")
    private Integer status;

    public BpmDelegateInfo() {
    }

    public BpmDelegateInfo(String assignee, String attorney, Date startTime,
            Date endTime, String processDefinitionId, Integer status) {
        this.assignee = assignee;
        this.attorney = attorney;
        this.startTime = startTime;
        this.endTime = endTime;
        this.processDefinitionId = processDefinitionId;
        this.status = status;
    }

    /** @return null. */
    public String getAssignee() {
        return this.assignee;
    }

    /**
     * @param assignee
     *            null.
     */
    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }

    /** @return null. */
    public String getAttorney() {
        return this.attorney;
    }

    /**
     * @param attorney
     *            null.
     */
    public void setAttorney(String attorney) {
        this.attorney = attorney;
    }

    /** @return null. */
    public Date getStartTime() {
        return this.startTime;
    }

    /**
     * @param startTime
     *            null.
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /** @return null. */
    public Date getEndTime() {
        return this.endTime;
    }

    /**
     * @param endTime
     *            null.
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /** @return null. */
    public String getProcessDefinitionId() {
        return this.processDefinitionId;
    }

    /**
     * @param processDefinitionId
     *            null.
     */
    public void setProcessDefinitionId(String processDefinitionId) {
        this.processDefinitionId = processDefinitionId;
    }

    /** @return null. */
    public Integer getStatus() {
        return this.status;
    }

    /**
     * @param status
     *            null.
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}
