package com.luna.bpm.process.entity;

// Generated by Hibernate Tools
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.luna.common.entity.BaseEntity;

/**
 * BpmDelegateHistory .
 * 
 * @author Lingo
 */
@Entity
@Table(name = "BPM_DELEGATE_HISTORY")
public class BpmDelegateHistory extends BaseEntity<Long> {
    private static final long serialVersionUID = 0L;

    @Column(name = "ASSIGNEE", length = 200)
    private String assignee;
    
    @Column(name = "ATTORNEY", length = 200)
    private String attorney;
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DELEGATE_TIME", length = 26)
    private Date delegateTime;
    
    @Column(name = "TASK_ID", length = 100)
    private String taskId;

    @Column(name = "STATUS")
    private Integer status;

    public BpmDelegateHistory() {
    }

    public BpmDelegateHistory(String assignee, String attorney,
            Date delegateTime, String taskId, Integer status) {
        this.assignee = assignee;
        this.attorney = attorney;
        this.delegateTime = delegateTime;
        this.taskId = taskId;
        this.status = status;
    }

    /** @return null. */
    public String getAssignee() {
        return this.assignee;
    }

    /**
     * @param assignee
     *            null.
     */
    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }

    /** @return null. */
    public String getAttorney() {
        return this.attorney;
    }

    /**
     * @param attorney
     *            null.
     */
    public void setAttorney(String attorney) {
        this.attorney = attorney;
    }

    /** @return null. */
    public Date getDelegateTime() {
        return this.delegateTime;
    }

    /**
     * @param delegateTime
     *            null.
     */
    public void setDelegateTime(Date delegateTime) {
        this.delegateTime = delegateTime;
    }

    /** @return null. */
    public String getTaskId() {
        return this.taskId;
    }

    /**
     * @param taskId
     *            null.
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    /** @return null. */
    public Integer getStatus() {
        return this.status;
    }

    /**
     * @param status
     *            null.
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}
