package com.luna.bpm.process.entity;

// Generated by Hibernate Tools
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.luna.common.entity.BaseEntity;

/**
 * BpmTaskDef .
 * 
 * @author Lingo
 */
@Entity
@Table(name = "BPM_TASK_DEF")
public class BpmTaskDef extends BaseEntity<Long> {
    private static final long serialVersionUID = 0L;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PROCESS_ID")
    private BpmProcess bpmProcess;

    @Column(name = "TASK_DEFINITION_KEY", length = 200)
    private String taskDefinitionKey;

    @Column(name = "ASSIGNEE", length = 200)
    private String assignee;

    @Column(name = "CANDIDATE", length = 200)
    private String candidate;

    public BpmTaskDef() {
    }

    public BpmTaskDef(BpmProcess bpmProcess, String taskDefinitionKey,
            String assignee, String candidate) {
        this.bpmProcess = bpmProcess;
        this.taskDefinitionKey = taskDefinitionKey;
        this.assignee = assignee;
        this.candidate = candidate;
    }

    /** @return null. */
    public BpmProcess getBpmProcess() {
        return this.bpmProcess;
    }

    /**
     * @param bpmProcess
     *            null.
     */
    public void setBpmProcess(BpmProcess bpmProcess) {
        this.bpmProcess = bpmProcess;
    }

    /** @return null. */
    public String getTaskDefinitionKey() {
        return this.taskDefinitionKey;
    }

    /**
     * @param taskDefinitionKey
     *            null.
     */
    public void setTaskDefinitionKey(String taskDefinitionKey) {
        this.taskDefinitionKey = taskDefinitionKey;
    }

    /** @return null. */
    public String getAssignee() {
        return this.assignee;
    }

    /**
     * @param assignee
     *            null.
     */
    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }

    /** @return null. */
    public String getCandidate() {
        return this.candidate;
    }

    /**
     * @param candidate
     *            null.
     */
    public void setCandidate(String candidate) {
        this.candidate = candidate;
    }
}
