package com.luna.bpm.process.entity;

// Generated by Hibernate Tools
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.luna.common.entity.BaseEntity;

/**
 * BpmTaskConf .
 * 
 * @author Lingo
 */
@Entity
@Table(name = "BPM_TASK_CONF")
public class BpmTaskConf extends BaseEntity<Long> {
    private static final long serialVersionUID = 0L;

    @Column(name = "BUSINESS_KEY", length = 200)
    private String businessKey;
    
    @Column(name = "TASK_DEFINITION_KEY", length = 200)
    private String taskDefinitionKey;
    
    @Column(name = "ASSIGNEE", length = 200)
    private String assignee;

    public BpmTaskConf() {
    }

    public BpmTaskConf(String businessKey, String taskDefinitionKey,
            String assignee) {
        this.businessKey = businessKey;
        this.taskDefinitionKey = taskDefinitionKey;
        this.assignee = assignee;
    }

    /** @return null. */
    public String getBusinessKey() {
        return this.businessKey;
    }

    /**
     * @param businessKey
     *            null.
     */
    public void setBusinessKey(String businessKey) {
        this.businessKey = businessKey;
    }

    /** @return null. */
    public String getTaskDefinitionKey() {
        return this.taskDefinitionKey;
    }

    /**
     * @param taskDefinitionKey
     *            null.
     */
    public void setTaskDefinitionKey(String taskDefinitionKey) {
        this.taskDefinitionKey = taskDefinitionKey;
    }

    /** @return null. */
    public String getAssignee() {
        return this.assignee;
    }

    /**
     * @param assignee
     *            null.
     */
    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }
}
